name: labplus_for_gitlab
description: Your mobile companion for Gitlab

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.5.0+2

environment:
  sdk: "^3.5.1"
  flutter: "^3.24.1"


dependencies:
  adaptive_theme: ^3.6.0
  build_runner: ^2.4.8
  cached_network_image: ^3.3.1
  date_time_picker: ^2.1.0
  dio: ^5.4.1
  file_icon: ^1.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_easyloading: ^3.0.5
  flutter_markdown: ^0.6.22
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.4
  get: ^4.6.6
  grouped_list: ^5.1.2
  intl: ^0.17.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # path: ^1.8.2
  share_plus: ^8.0.0
  shared_preferences: ^2.2.2
  sticky_headers: ^0.3.0+2
  timeago: ^3.2.2
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  package_info_plus: ^6.0.0
  rxdart: ^0.27.7
  path: ^1.9.0
  string_scanner: ^1.2.0
  timelines:  ^0.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/2.svg

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Black.ttf
        - asset: fonts/SourceCodePro-BlackIt.ttf
        - asset: fonts/SourceCodePro-Bold.ttf
        - asset: fonts/SourceCodePro-BoldIt.ttf
        - asset: fonts/SourceCodePro-ExtraLight.ttf
        - asset: fonts/SourceCodePro-ExtraLightIt.ttf
        - asset: fonts/SourceCodePro-It.ttf
        - asset: fonts/SourceCodePro-Light.ttf
        - asset: fonts/SourceCodePro-Medium.ttf
        - asset: fonts/SourceCodePro-MediumIt.ttf
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-Semibold.ttf
        - asset: fonts/SourceCodePro-SemiboldIt.ttf

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: "#ffffff"
  color_dark: "#330d69"
  image: assets/splash_400.png
  android: true
  ios: true
  web: false
